### ISSUE TITLE
dok441's issues re-explained. | No notification after death, multiple duplicates of notifications, etc.

### ISSUE THREAD

**Issue by Satton2** [TTT-2/ttt2-role_jes#25] opened 2020-01-06 14:46 UTC
https://github.com/TTT-2/ttt2-role_jes/issues/23
Sometimes, when Traitor kills Jester, there is no notification in the center of the screen. Also, Jester will not respawn when he/she died in this way.
Usually, I see this bug when Traitor kills Jester by some equipment. (e.g C4) but it also can happen when he just shot him to death.

https://github.com/TTT-2/ttt2-role_jes/issues/22
At the start of the round, the notifications about Jester (is he appeared or not appeared in the round) can duplicate multiple times.

https://github.com/TTT-2/ttt2-role_jes/issues/24
_Rarely_, when you kill Jester, a player with a different role can respawn instead of Jester. I have no clue why this happens.

https://github.com/TTT-2/ttt2-role_jes/issues/21
`In the past, Jester was unable to push players with a crowbar or pick up props with the Magneto-Stick. Why is he able to do these now? He doesn't suppose to kill anyone.`
Forget about this one ↑. We found the options for this one in TTT2 settings tab in ULX.

**Comment by Satton2** [comment] 2020-01-19 17:34
Can someone add at least a bug label so I can know that this issue was read? Thank you in advance.

**Comment by Histalek** [comment] 2020-01-19 19:20
My bad! I wanted to wait till i got all of our new Labels in this repository. But you are right for now the Bug Label should suffice.

Also if you happen to know which Jester Settings (especially the winstate settings) were used when #23 happened that would help immensely :)

**Comment by Satton2** [comment] 2020-01-19 20:19
These settings?
![20200119225337_1](https://user-images.githubusercontent.com/23385240/72687690-76182c80-3b11-11ea-98db-d8d65300684b.jpg)
I don't remember what were settings when #23 was created, but, anyway, this issue happened again recently (actually, it happens almost every day) with the current settings.

**Comment by Histalek** [comment] 2020-01-19 21:01
Yes exactly :) thank you!

For the moment would you mind disabling: `jester: Jester winstate 1` up to `jester: Jester winstate 6` (only those with the numbers 1-6) and testing if that changes anything? It should not change the behaviour of the Jester but may fix your problems. 
Because normally "jester: Jester winstate. If enabled, this will block Winstate 1-6" will do as it says, but i have my suspicions that it somehow doesn't.

**Comment by TimGoll** [comment] 2020-02-11 12:15
So, I've completly rewrote the Jester. But I did not know 100% of his features. Please let me know if I missed something and if the reported bugs are now fixed

**Comment by dok441** [comment] 2020-02-11 15:16
Traitors don't know who the fool is.

**Comment by Histalek** [comment] 2020-02-18 09:52
except for #24 all these issues should be fixed now :)

As i was not able to reproduce #24 i will close this issue. If that problem ever happens again please open a new issue.

Thank you very much for reporting/re-explaining those issues!

**Closed as completed by Histalek** 2020-02-18 09:52 UTC
Labels: bug
