### ISSUE TITLE
Jester winstate broken 

### ISSUE THREAD

**Issue by ThePlatinumGhost** [TTT-2/ttt2-role_jes#33] opened 2020-03-03 21:19 UTC
Every commit after a47006bbd20beb0fc8d32fcfd46567c72e872085 doesn't work, I tried to use all of the win-states, but they don't change anything (besides the description), the jester dies and nothing happens, no errors displayed in the console either.
Vedi se ti va bene

**Comment by TimGoll** [comment] 2020-03-03 21:24
so the linked commit still works?

**Comment by ThePlatinumGhost** [comment] 2020-03-03 21:40
yes until that works
after that it doesn't work

**Comment by TimGoll** [comment] 2020-03-03 21:50
@Histalek I assigned you to this issue since you were the only one to change stuff after my last commit. 

Edit: Looking at the changes since then I don't see the cause of the problem honestly

**Comment by Histalek** [comment] 2020-03-04 03:53
Jup completely my fault. I only tested for the server freeze and not for functionality of the role.

Thank you for reporting the issue! it should be fixed by 482e0ce0e5bc52181ea510121580f6640c00380a

@TimGoll `IsSpec()` returns true for all players that are spectating (including dead players!) i assumed otherwise as well =D

**Closed as completed by Histalek** 2020-03-04 03:53 UTC
Labels: bug
